[package]
name = "tso"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = {version = "0.22.1", features = ["lexer", "unicode"]}
thiserror = "2.0.11"

[build-dependencies]
lalrpop = "0.22.1"
